# Generated by Django 2.2.10 on 2020-04-14 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='Organization Code')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Organization Name')),
            ],
        ),
    ]
