# Generated by Django 2.2.10 on 2020-03-26 09:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Undss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Shape', models.BinaryField()),
                ('Data_Entry_No', models.TextField()),
                ('Date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('Time_of_Incident', models.CharField(max_length=255)),
                ('Province', models.CharField(max_length=255)),
                ('District', models.CharField(max_length=255)),
                ('City_Village', models.CharField(max_length=255)),
                ('Area', models.CharField(max_length=255)),
                ('Police_District', models.CharField(max_length=255)),
                ('Incident_Type', models.CharField(max_length=255)),
                ('Incident_Subtype', models.CharField(max_length=255)),
                ('Description_of_Incident', models.CharField(max_length=255)),
                ('HPA', models.CharField(max_length=255)),
                ('Initiator', models.CharField(max_length=255)),
                ('Target', models.CharField(max_length=255)),
                ('killed', models.IntegerField()),
                ('Field16', models.CharField(max_length=255)),
                ('Field17', models.IntegerField()),
                ('Field18', models.CharField(max_length=255)),
                ('Field19', models.IntegerField()),
                ('Field20', models.IntegerField()),
                ('Field21', models.CharField(max_length=255)),
                ('Injured', models.IntegerField()),
                ('Field23', models.CharField(max_length=255)),
                ('Field24', models.IntegerField()),
                ('Field25', models.CharField(max_length=255)),
                ('Field26', models.IntegerField()),
                ('Field27', models.IntegerField()),
                ('Field28', models.CharField(max_length=255)),
                ('Abducted', models.FloatField()),
                ('Field30', models.CharField(max_length=255)),
                ('Field31', models.IntegerField()),
                ('Field32', models.CharField(max_length=255)),
                ('Field33', models.CharField(max_length=255)),
                ('Latitude', models.FloatField()),
                ('Longitude', models.FloatField()),
                ('PRMO', models.CharField(max_length=255)),
                ('UNDSS', models.CharField(max_length=255)),
                ('INSO', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
