# Generated by Django 2.2.10 on 2020-11-23 03:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        ('reference', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Undss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Single_ID', models.CharField(max_length=50, null=True, verbose_name='Data Entry No')),
                ('Date', models.DateField(null=True, verbose_name='Date')),
                ('Time_of_Incident', models.TimeField(default=datetime.time(0, 0), verbose_name='Time Of Incident')),
                ('City_Village', models.CharField(blank=True, max_length=255, null=True, verbose_name='City Village')),
                ('Area', models.CharField(blank=True, max_length=255, null=True, verbose_name='Area')),
                ('Police_District', models.CharField(blank=True, max_length=255, null=True)),
                ('Description_of_Incident', models.TextField(blank=True, null=True, verbose_name='Description of Incident')),
                ('HPA', models.CharField(blank=True, max_length=255, null=True)),
                ('Kill_Natl', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Killed - National')),
                ('Kill_Intl', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Killed - International')),
                ('Kill_ANSF', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Killed - ANSF')),
                ('Kill_IM', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Killed - IM')),
                ('Kill_ALP_PGM', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Killed - ALP_PGM')),
                ('Kill_AOG', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Killed - AOG')),
                ('Kill_ISKP', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Killed - ISKP')),
                ('Inj_Natl', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Injured - National')),
                ('Inj_Intl', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Injured - International')),
                ('Inj_ANSF', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Injured - ANSF')),
                ('Inj_IM', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Injured - IM')),
                ('Inj_ALP_PGM', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Injured - ALP_PGM')),
                ('Inj_AOG', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Injured - AOG')),
                ('Inj_ISKP', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Injured - ISKP')),
                ('Abd_Natl', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Abducted - National')),
                ('Abd_Intl', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Abducted - International')),
                ('Abd_ANSF', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Abducted - ANSF')),
                ('Abd_IM', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Abducted - IM')),
                ('Abd_ALP_PGM', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Abducted - ALP_PGM')),
                ('Latitude', models.FloatField(blank=True, null=True)),
                ('Longitude', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('District', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reference.District', verbose_name='District')),
                ('Incident_Source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reference.IncidentSource')),
                ('Incident_Subtype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reference.IncidentSubtype', verbose_name='Incident SubType')),
                ('Incident_Type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reference.IncidentType', verbose_name='Incident Type')),
                ('Initiator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Organization_initiator_name', to='organization.Organization')),
                ('Province', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reference.Province', verbose_name='Province')),
                ('Target', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Organization_target_name', to='organization.Organization')),
            ],
        ),
    ]
