# Generated by Django 2.2.10 on 2020-04-14 03:14

import dashboard.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='undss',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterField(
            model_name='undss',
            name='Abducted',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='undss',
            name='Area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reference.Area', verbose_name='Area'),
        ),
        migrations.AlterField(
            model_name='undss',
            name='City_Village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reference.CityVillage', verbose_name='City Village'),
        ),
        migrations.AlterField(
            model_name='undss',
            name='Data_Entry_No',
            field=models.CharField(max_length=50, verbose_name='Data Entry No'),
        ),
        migrations.AlterField(
            model_name='undss',
            name='Date',
            field=models.DateTimeField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='undss',
            name='Description_of_Incident',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='undss',
            name='District',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reference.District', verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='undss',
            name='Field16',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='undss',
            name='Field17',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='undss',
            name='Field18',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='undss',
            name='Field19',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='undss',
            name='Field20',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='undss',
            name='Field21',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='undss',
            name='Field23',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='undss',
            name='Field24',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='undss',
            name='Field25',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='undss',
            name='Field26',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='undss',
            name='Field27',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='undss',
            name='Field28',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='undss',
            name='Field30',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='undss',
            name='Field31',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='undss',
            name='Field32',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='undss',
            name='Field33',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='undss',
            name='HPA',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='undss',
            name='INSO',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='undss',
            name='Incident_Subtype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reference.IncidentSubtype', verbose_name='Incidenet SubType'),
        ),
        migrations.AlterField(
            model_name='undss',
            name='Incident_Type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reference.IncidentType', verbose_name='Incident Type'),
        ),
        migrations.AlterField(
            model_name='undss',
            name='Initiator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Organization_initiator_name', to='organization.Organization'),
        ),
        migrations.AlterField(
            model_name='undss',
            name='Injured',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='undss',
            name='Latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='undss',
            name='Longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='undss',
            name='PRMO',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='undss',
            name='Police_District',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='undss',
            name='Province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reference.Province', verbose_name='Province'),
        ),
        migrations.AlterField(
            model_name='undss',
            name='Shape',
            field=models.FileField(blank=True, null=True, upload_to=dashboard.models.PathAndRename('shape/'), verbose_name='Shape'),
        ),
        migrations.AlterField(
            model_name='undss',
            name='Target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Organization_target_name', to='organization.Organization'),
        ),
        migrations.AlterField(
            model_name='undss',
            name='Time_of_Incident',
            field=models.TimeField(default=dashboard.models.default_start_time, verbose_name='Time Of Incident'),
        ),
        migrations.AlterField(
            model_name='undss',
            name='UNDSS',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='undss',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='undss',
            name='killed',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='undss',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
