# Generated by Django 2.2.10 on 2020-11-12 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='undss',
            name='Shape',
        ),
    ]
