# Generated by Django 2.2.10 on 2020-11-12 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_undss_shape'),
    ]

    operations = [
        migrations.AlterField(
            model_name='undss',
            name='Abd_Intl',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Abducted - International'),
        ),
        migrations.AlterField(
            model_name='undss',
            name='Abd_Natl',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Abducted - National'),
        ),
        migrations.AlterField(
            model_name='undss',
            name='Area',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Area'),
        ),
        migrations.AlterField(
            model_name='undss',
            name='City_Village',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='City Village'),
        ),
        migrations.AlterField(
            model_name='undss',
            name='Inj_Intl',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Injured - International'),
        ),
        migrations.AlterField(
            model_name='undss',
            name='Inj_Natl',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Injured - National'),
        ),
        migrations.AlterField(
            model_name='undss',
            name='Kill_Intl',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Killed - International'),
        ),
        migrations.AlterField(
            model_name='undss',
            name='Kill_Natl',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Killed - National'),
        ),
    ]
