# Generated by Django 2.2.10 on 2020-11-02 07:42

import dashboard.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0002_incidentsource'),
        ('dashboard', '0002_auto_20200414_0314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='undss',
            name='INSO',
        ),
        migrations.RemoveField(
            model_name='undss',
            name='PRMO',
        ),
        migrations.RemoveField(
            model_name='undss',
            name='UNDSS',
        ),
        migrations.AddField(
            model_name='undss',
            name='Incident_Source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reference.IncidentSource'),
        ),
        migrations.AlterField(
            model_name='undss',
            name='Data_Entry_No',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Data Entry No'),
        ),
        migrations.AlterField(
            model_name='undss',
            name='Date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='undss',
            name='Incident_Subtype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reference.IncidentSubtype', verbose_name='Incident SubType'),
        ),
        migrations.AlterField(
            model_name='undss',
            name='Time_of_Incident',
            field=models.TimeField(blank=True, default=dashboard.models.default_start_time, null=True, verbose_name='Time Of Incident'),
        ),
    ]
