# Generated by Django 2.2.10 on 2020-11-13 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20201112_0726'),
    ]

    operations = [
        migrations.RenameField(
            model_name='undss',
            old_name='Data_Entry_No',
            new_name='Single_ID',
        ),
    ]
